FROM node:20-bookworm-slim AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

# Variables necesarias en build time para páginas prerenderizadas
ARG TURNSTILE_SITE_KEY
ENV TURNSTILE_SITE_KEY=$TURNSTILE_SITE_KEY
ARG API_URL
ENV API_URL=$API_URL
ARG API_KEY_LANDING
ENV API_KEY_LANDING=$API_KEY_LANDING

ARG PUBLIC_PAGOPAR_PROVIDER_SELECTOR_ENABLED=true
ENV PUBLIC_PAGOPAR_PROVIDER_SELECTOR_ENABLED=$PUBLIC_PAGOPAR_PROVIDER_SELECTOR_ENABLED

# Astro incorpora estos IDs durante el build. Dokploy debe enviarlos como build args.
ARG PUBLIC_ESSENTIAL_PLAN_ID
ENV PUBLIC_ESSENTIAL_PLAN_ID=$PUBLIC_ESSENTIAL_PLAN_ID
ARG PUBLIC_PLUS_PLAN_ID
ENV PUBLIC_PLUS_PLAN_ID=$PUBLIC_PLUS_PLAN_ID
ARG PUBLIC_BLACK_PLAN_ID
ENV PUBLIC_BLACK_PLAN_ID=$PUBLIC_BLACK_PLAN_ID
ARG PUBLIC_DOMICILIO_PLAN_ID
ENV PUBLIC_DOMICILIO_PLAN_ID=$PUBLIC_DOMICILIO_PLAN_ID
ARG PUBLIC_GOLD_PLAN_ID
ENV PUBLIC_GOLD_PLAN_ID=$PUBLIC_GOLD_PLAN_ID
ARG PUBLIC_LEGACY_FORMULA_PLAN_ID
ENV PUBLIC_LEGACY_FORMULA_PLAN_ID=$PUBLIC_LEGACY_FORMULA_PLAN_ID
ARG PUBLIC_LEGACY_PREMIUM_PLAN_ID
ENV PUBLIC_LEGACY_PREMIUM_PLAN_ID=$PUBLIC_LEGACY_PREMIUM_PLAN_ID
ARG PUBLIC_LEGACY_GOLD_PLAN_ID
ENV PUBLIC_LEGACY_GOLD_PLAN_ID=$PUBLIC_LEGACY_GOLD_PLAN_ID

RUN npm run build

FROM node:20-bookworm-slim AS runtime
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules

ENV HOST=0.0.0.0
ENV PORT=80
EXPOSE 80
CMD ["node", "dist/server/entry.mjs"]
